image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
  #  - step:
      #  name: maven package
      #  caches:
      #    - maven
      #  script:
         # - mvn package 
         # - ls target/
    - step:
          name: Ansible
          image: ansible/ansible
          caches:
                  - maven
          script: 
             - ansible-playbook -i inventory -u testing playbook.yml