image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - pwd
          - mvn clean
          - mvn package
          - ls target/
          - ls -la
          - pwd
          - find "$(cd ..; pwd)" -name "target"
          - realpath -e target
          #- cd /opt/atlassian/pipelines/agent/build/target
          - pwd


    - step:
           name: upload artifacts
           image: maven:3.3-jdk-8
           script:
          # Install JFrog CLI
           - curl -fL https://getcli.jfrog.io | sh
          # Configure Artifactory instance with JFrog CLI
           - ./jfrog rt config artifactory --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --interactive false
          # Maven command to build project
           - mvn clean install
          # Upload created artifacts to Artifactory
           - ./jfrog rt u "target/debitcardcustomer-0.0.1-SNAPSHOT.war" "debit-card-application-dev/" --build-name="sample-slack-debitcardapp-feature-2" --build-number=$BITBUCKET_BUILD_NUMBER


