image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - pwd
          - mvn clean
          - mvn package
          - ls target/
          - ls -la
          - pwd
          - find "$(cd ..; pwd)" -name "target"
          - realpath -e target
          - cd /opt/atlassian/pipelines/agent/build/target/
          - pwd
    - step:
        name: uploading artifacts
        script:
         - pipe: JfrogDev/artifactory-generic-upload:0.3.2
           variables:
            ARTIFACTORY_URL: $url
            ARTIFACTORY_USER: $user
            ARTIFACTORY_PASSWORD: $pass
            FILE_SPEC: "false"
            SOURCE_PATH: "target/"
            TARGET_PATH: "debit-card-application-dev/"