image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
    - step:
        name: maven package
        caches:
          - maven
        script:
          - mvn package 
          - ls target/
    - step:
         name: Snyk test
         caches:
         - maven
         script:
           - apt-get update && apt-get install -y nodejs
           - npm install -g snyk
           - mvn -B install
           - snyk auth $SNYK_TKN
           - snyk test --all-projects
           - pipe: snyk/snyk-scan:0.4.3              
             variables:
               SNYK_TOKEN: $SNYK_TKN
                   
    - step:
        name: Artifactory Upload
        caches:
          - maven
        script:
          - pipe: JfrogDev/artifactory-maven:0.3.3
            variables:
                  ARTIFACTORY_URL: $url
                  ARTIFACTORY_USER: $user
                  ARTIFACTORY_PASSWORD: $pass
                  MAVEN_SNAPSHOT_REPO: 'debitcardcustomer-0.0.1-SNAPSHOT.war'
                  MAVEN_RELEASE_REPO: 'dev-debit-bit'
    
   