image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
    - step:
        name: maven package
        caches:
          - maven
        script:
          - mvn package 
          - ls target/
    - step:
        name: Sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.1.0
            variables:
             EXTRA_ARGS: -Dsonar.projectDescription=\"Project with sonarcloud-scan pipe\" 
             SONAR_SCANNER_OPTS: -Xmx512m
             DEBUG: "true"
    
   