image: maven:3.3.9

clone:
  depth: full              

definitions:
  caches:
    sonar: ~/.sonar/cache  
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - maven
          - sonar
        script:
                    - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        artifacts:
                    - target/**
    - step: &build-test
                  name: Build and test
                  caches:
                    - maven
                  script:
                    - mvn -B verify
                  artifacts:
                  - target/**
                  pipelines:
                    default:
                      - step: *build-test
                    branches:
                      master:
                        - step: *build-test-sonarcloud
                    pull-requests:
                      '**':
                        - step: *build-test-sonarcloud

   