image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
    - step:
        name: maven package
        caches:
          - maven
        script:
          - mvn package 
          - ls target/
 

        clone:
        depth: full              

        definitions:
         caches:
         sonar: ~/.sonar/cache  
      steps:
       - step: &build-test-sonarcloud
           name: Build, test and analyze on SonarCloud
           caches:
             - maven
             - sonar
           script:
             - mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
           artifacts:
             - target/**

      pipelines:                 
       branches:
       master:
         - step: *build-test-sonarcloud
      pull-requests:
       '**':
         - step: *build-test-sonarcloud

                    
  
    - step:
        script:
                 - pipe: JfrogDev/artifactory-generic-upload:0.3.2
                   variables:
                     ARTIFACTORY_URL: $url
                     ARTIFACTORY_USER: $user
                     ARTIFACTORY_PASSWORD: $pass
                    #FILE_SPEC: 'false'
                     SOURCE_PATH: 'debitcardcustomer-0.0.1-SNAPSHOT.war'
                     TARGET_PATH: 'debit-card-application-dev/'
                   #  MAVEN_RELEASE_REPO: 'debitcardcustomer-0.0.1-SNAPSHOT.war'
    
   