image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
    - step:
            name: maven compile
            caches:
              - maven
            script:
              - mvn compile
    - step:
            name: Sonar
            script:
              - mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
              - pipe: sonarsource/sonarcloud-scan:1.1.0
                variables:
                 SONAR_TOKEN: '$SONAR_TOKEN'
                 SONAR_SCANNER_OPTS: -Xmx512m
                 DEBUG: "true"
    - step:
        name: maven package
        caches:
          - maven
        script:
          - mvn package 
          - ls target/
    
    
   