image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
    
    - step:
            name: uploading artifacts
            script:
                     - curl -fL https://getcli.jfrog.io | sh
                     - pipe: JfrogDev/artifactory-maven:0.3.3
                       variables:
                         ARTIFACTORY_URL: $url
                         ARTIFACTORY_USER: $user
                         ARTIFACTORY_PASSWORD: $pass
                         MAVEN_SNAPSHOT_REPO: "debit-card-application-dev/"
                         MAVEN_RELEASE_REPO: "debit-card-application-dev/"
    