image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
    
    - step:
            name: uploading artifacts
            script:
                     - pipe: JfrogDev/artifactory-generic-upload:0.2.11
                       variables:
                         ARTIFACTORY_URL: $url
                         ARTIFACTORY_USER: $user
                         ARTIFACTORY_PASSWORD: $pass
                         FILE_SPEC: "false"
                         SOURCE_PATH: "target/*.war"
                         TARGET_PATH: "debit-card-application-dev/"
                         BUILD_NAME: "example"
    