image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
    - step:
        name: maven package
        caches:
          - maven
        script:
          - mvn package 
          - ls target/
   
                    
  
    - step:
        script:
                 - pipe: JfrogDev/artifactory-generic-upload:0.3.2
                   variables:
                     ARTIFACTORY_URL: $url
                     ARTIFACTORY_USER: $user
                     ARTIFACTORY_PASSWORD: $pass
                     FILE_SPEC: 'false'
                     SOURCE_PATH: 'debitcardcustomer-0.0.1-SNAPSHOT.war'
                     TARGET_PATH: 'debit-card-sample/'
                   #  MAVEN_RELEASE_REPO: 'debitcardcustomer-0.0.1-SNAPSHOT.war'
    
   