image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
    - step:
       script:   
       - pipe: sonarsource/sonarcloud-scan:0.1.5
         variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.sources=src/'
              SONAR_SCANNER_OPTS: -Xmx512m
              DEBUG: "false"

    - step:
        name: maven package
        caches:
          - maven
        script:
          - mvn package 
          - ls target/


 
   