image: maven:3.6.1

pipelines:
  default:
    - step:
        name: maven clean
        caches:
          - maven
        script:
          - mvn clean
          - mvn package
    
    - step:
            name: uploading artifacts
            script:
                     - pipe: JfrogDev/artifactory-generic-upload:0.2.11
                       variables:
                         ARTIFACTORY_URL: $url
                         ARTIFACTORY_USER: $user
                         ARTIFACTORY_PASSWORD: $pass
                         FILE_SPEC: "false"
                         MAVEN_SNAPSHOT_REPO: 'debit-card-application-dev/'
                         MAVEN_RELEASE_REPO: 'debit-card-application-dev/'
                         MAVEN_COMMAND: 'clean test install'
                         FOLDER: 'DebitCardApp'
    